import {Frase} from '../shared/frase.model'

export const FRASES: Array<Frase> = [
        { fraseEng:'I like to learn', frasePtBr:'Eu gosto de aprender'},
        { fraseEng:'How are you?', frasePtBr:'Como vai você?'},
        { fraseEng:'What is your name?', frasePtBr:'Qual é o seu nome'},
        { fraseEng:'My dog is brown', frasePtBr:'Meu cão é marrom'},
        { fraseEng:'The chair is white', frasePtBr:'A cadeira é branca'},
        { fraseEng:'Bread is my favourite food', frasePtBr:'Pão é a minha comida favorita'},       
        {fraseEng:"My name is Jake."                     , frasePtBr:"Meu nome é Jake."},
        {fraseEng:"Hello. How are you?"                  , frasePtBr:"Oi. Como vai você?"}, 
        {fraseEng:"I am fine, and you?"                  , frasePtBr:"Eu estou bem, e você?"},
        {fraseEng:"Nice to meet you!  "                  , frasePtBr:"Prazer em te conhecer!"},
        {fraseEng:"Nice to meet you too."                , frasePtBr:"O prazer é meu."},
        {fraseEng:"What time is it?      "               , frasePtBr:"Que horas são?"},
        {fraseEng:"I am hungry!"                         , frasePtBr:"Estou com fome!"},
        {fraseEng:"I am thirsty!"                        , frasePtBr:"Estou com sede!"},
        {fraseEng:" I am hot.    "                       , frasePtBr:"Eu estou com calor."},
        {fraseEng:" I am cold.    "                      , frasePtBr:"Estou com frio."},
        {fraseEng:" How old are you?"                    , frasePtBr:"Qual é a sua idade?"},
        {fraseEng:" Where are you from?"                 , frasePtBr:"De onde você é?"},
        {fraseEng:" I'm from Brazil.    "                , frasePtBr:"Eu sou do Brasil."},
        {fraseEng:" Please.   "                          , frasePtBr:"Por favor."},
        {fraseEng:" Excuse me. "                         , frasePtBr:"Com licença."},
        {fraseEng:" I'm sorry.  "                        , frasePtBr:"Desculpa."},
        {fraseEng:" Have a nice weekend."                , frasePtBr:"Tenha um bom final de semana."},
        {fraseEng:" Where do you live? "                 , frasePtBr:"Onde você mora?"},
        {fraseEng:" Are you married or single? "         , frasePtBr:"Você é casado ou solteiro?"},
        {fraseEng:" What do you do? I am a lawyer."      , frasePtBr:"Qual é a sua profissão? Eu sou advogado."},
        
        {fraseEng:" Do you have any children?  "         , frasePtBr:"Você tem filhos?"},
        {fraseEng:" Do you have any brothers or sisters?", frasePtBr:"Você tem irmãos ou irmãs?"},
        {fraseEng:" I'm late. "                          , frasePtBr:"Estou atrasado."},
        {fraseEng:" I miss you."                         , frasePtBr:"Estou com saudades de você."},
        {fraseEng:" I'm sorry I'm late."                 , frasePtBr:"Desculpe o atraso."},
        {fraseEng:" Can I help you?"                     , frasePtBr:"Posso ajudar?"},
        {fraseEng:" Can you help me?"                    , frasePtBr:"Você pode me ajudar?"},
        {fraseEng:" How is the weather?"                 , frasePtBr:"Como está o clima?"},
        {fraseEng:" I love you."                         , frasePtBr:"Eu te amo."},
        {fraseEng:" I need."                             , frasePtBr:"Eu preciso."},
        {fraseEng:" I want. "                            , frasePtBr:"Eu quero."},
        {fraseEng:" I know.  "                           , frasePtBr:"Eu sei."},
        {fraseEng:" I don't know."                       , frasePtBr:"Eu não sei."},
        {fraseEng:" I knew. "                            , frasePtBr:"Eu sabia."}, 
        {fraseEng:" I didn't know."                      , frasePtBr:"Eu não sabia."}, 
        {fraseEng:" Would you like some juice? "         , frasePtBr:"Você gostaria de um suco?"},
        {fraseEng:" Where is the restroom / bathroom? "  , frasePtBr:"Onde é o banheiro?"},
        {fraseEng:" I like ice cream. "                  , frasePtBr:"Eu gosto de sorvete."},
        {fraseEng:" Stop. Don't go. Stay here. "         , frasePtBr:"Pare. Não vá. Fique aqui."},
        {fraseEng:" What do you think about Brazil?"     , frasePtBr:"O que você acha do Brasil?"},
        {fraseEng:" I think Brazil is a great country."  , frasePtBr:"Eu acho o Brasil um ótimo país."},
        {fraseEng:" Be careful. It's dangerous.  "       , frasePtBr:"Tenha cuidado. É perigoso."},
        {fraseEng:" I agree with you."                   , frasePtBr:"Eu concordo com você."},
        {fraseEng:" Are you OK?  "                       , frasePtBr:"Está tudo bem com você?"},
        {fraseEng:" I'm not well. "                      , frasePtBr:"Eu não estou bem."},
        {fraseEng:" Good luck.    "                      , frasePtBr:"Boa sorte."},
        {fraseEng:" Have a nice trip. "                  , frasePtBr:"Boa viagem."},
        {fraseEng:" When is your birthday? "             , frasePtBr:"Quando é o seu aniversário?"},
        {fraseEng:" Is there a hotel near here?  "       , frasePtBr:"Tem um hotel aqui perto?"},
        {fraseEng:" Enjoy your meal!  "                  , frasePtBr:"Bom apetite!"},
        {fraseEng:" Get well soon!  "                    , frasePtBr:"Fique bem logo!"},
        {fraseEng:" Have fun!  "                         , frasePtBr:"Divirta-se!"},
        {fraseEng:" Please wait a moment. "              , frasePtBr:"Por favor, espere um momento."},
        {fraseEng:" Let's go. It's time.   "             , frasePtBr:"Vamos. Está na hora."},
        {fraseEng:" Don't speak loudly.     "            , frasePtBr:"Não fale alto."},
        {fraseEng:" Could you please speak more slowly? ", frasePtBr:"Você poderia por favor falar mais devagar?"}
        
]